### ISSUE TITLE
Colormap: Color of "Low" values too similar to background colors

### ISSUE THREAD

**Issue by klieret** [dhaitz/matplotlib-stylesheets#3]
First off: I love this style. However for plots that make use of the colormap (for example together with a scatter plot), the colors towards the bottom of the color scale blend in with the background:

![image](https://user-images.githubusercontent.com/13602468/187037155-135d50f6-f590-433e-be5d-522d9924adc5.png)

**Comment by dhaitz** [comment]
Thanks for reporting this observation! I guess this colormap makes most sense for a heatmap, where low values correspond to the light end of the color scale. For scatter plots, `magma` or `plasma` might be a better choice, although they might also blend in at the upper end of the scale? See https://matplotlib.org/stable/tutorials/colors/colormaps.html
I think the current default is sensible
